### ISSUE TITLE
[BUG] Despues de entrar a SBCS desde home rompe

### ISSUE THREAD

**Issue by sennedjem** [eallegretta/paletools#17]
Home -> Desafio de creacion de plantillas(desde el grid de home, no desde tab bar de la izq) -> Click en algunas de las opciones del tab bar, por ej plantillas

Siguiendo esos pasos rompe y se queda colgado

![image](https://user-images.githubusercontent.com/13736226/151222317-0efc6631-790f-4f57-827f-0526acccf743.png)

**Comment by eallegretta** [comment]
Esto me parece que es un bug de EA y no mío

**Comment by eallegretta** [comment]
Arreglado en 1.0.12
