### ISSUE TITLE
[Enhancement] Recargar pagina/borrar cache y poder mandar jugadores al club desde ambos limbos

### ISSUE THREAD

**Issue by nicolaskaco** [eallegretta/paletools#20]
En general cuando termino un SBC y tengo jugadores repetidos en limbo clasico y watchlist, los jugadores no me aparecen para ser enviados al club.
Tengo que hacer:
1- Ir a lista de transferencias, cambiar un jugador de la lista al club 'Swap duplicate item from Club'
2- O refrescar la web app

Luego de hacer 1 o 2 ahi recien se 'refresca' el limbo/watchlist y los puedo enviar.

Basicamente vos tendrias que hacer un minimo 'recargar' cuando abrimos el limbo/watchlist.

**Comment by eallegretta** [comment]
Esto para mi es un bug de la webapp que EA eventualmente tiene que arreglar pero voy a ver si puedo hacer algo al respecto

**Comment by eallegretta** [comment]
Arreglado en 1.0.12
