### ISSUE TITLE
[Enhancement] Quiero dejar de mandar a Mbappe en sbc

### ISSUE THREAD

**Issue by Golsonica** [eallegretta/paletools#22]
Holis, tengo una pequeña sugerencia
Me quedé pelada haciendo las mejoras en la webapp porque cada vez que autocompletaba la plantilla, me tiraba cada dos por tres al Bicho o a Mbappe y como una boluda me fumé a Mendy y a Kimpembe un par de veces por la media baja y porque soy colgada (?
Hay chance de agregar una función como candadito que te bloquee X jugador para que no sea elegible en sbc? o un filtro que a partir de tal media, no se manden los jugadores picados (como un límite hasta no sé, 83 de media)?
Gracias totales

**Comment by eallegretta** [comment]
Tengo pensado agregar un limite por valor de media minima y maxima

**Comment by eallegretta** [comment]
Arreglado en 1.0.13
