### ISSUE TITLE
No funciona correctamente el boton de buscar el mas barato

### ISSUE THREAD

**Issue by Miguelhl77** [eallegretta/paletools#35]
Cuando habilitas el boton de ir al mas barato en una busqueda , no funciona cosa que en la version 23.1.0 si lo hacia perfectamente

**Comment by Miguelhl77** [comment]
El boton de buscar el jugador mas barato tambien da fallo habitualmente sale error

**Comment by eallegretta** [comment]
Arreglado en  23.9.8
